'use client';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { QueryClient, QueryClientProvider } from 'react-query';

import { Header } from '@/components/Header';
import GlobalStyle from '@/styles/global';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <>
      <QueryClientProvider client={queryClient}>
        <GlobalStyle />
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
        </html>
      </QueryClientProvider>
    </>
  );
}
